import pandas as pd
import os

# -------------------------
# LOAD CSVs GENERATED BY BOT
# -------------------------
events = pd.read_csv("data/match_events.csv")
lineups = pd.read_csv("data/match_lineups.csv")
stats = pd.read_csv("data/match_stats.csv")


# -------------------------
# POSITION MAP (FROM LINEUPS)
# -------------------------
pos_map = {}

for _, r in lineups.iterrows():
    pos_map[r["player"]] = r["position"]

def get_pos(player):
    return pos_map.get(player, "MF")


# -------------------------
# EVENT SCORING (YOUR SYSTEM START POINT)
# -------------------------
def score_event(row):
    t = str(row["type"]).lower()
    d = str(row["detail"]).lower()

    score = 0

    if t == "goal":
        score += 1.0 if "penalty" not in d else 0.75

    if "subst" in t:
        score += 0.1

    if "yellow" in d:
        score -= 0.3

    if "red" in d:
        score -= 1.0

    return score


events["score"] = events.apply(score_event, axis=1)


# -------------------------
# PLAYER TOTALS
# -------------------------
player_scores = events.groupby("player")["score"].sum().reset_index()


# -------------------------
# TEAM CONTEXT (LIGHT BONUS FROM STATS)
# -------------------------
team_bonus = {}

for _, r in stats.iterrows():
    if "possession" in str(r["stat"]).lower():
        try:
            v = float(str(r["value"]).replace("%", ""))
            team_bonus[r["team"]] = (v - 50) * 0.01
        except:
            pass


# -------------------------
# BUILD RATINGS
# -------------------------
rows = []

for _, r in player_scores.iterrows():

    player = r["player"]
    base = 6.0
    score = r["score"]

    pos = get_pos(player)

    # find team
    team = events[events["player"] == player]["team"].iloc[0]

    bonus = team_bonus.get(team, 0)

    # POSITION MODEL (YOUR STRUCTURE)
    if pos == "DF":
        rating = base + score * 1.2 + bonus
    elif pos == "FW":
        rating = base + score * 1.5 + bonus
    elif pos == "MF":
        rating = base + score * 1.3 + bonus
    elif pos == "GK":
        rating = base + score * 1.1 + bonus
    else:
        rating = base + score + bonus

    rows.append({
        "player": player,
        "team": team,
        "position": pos,
        "rating": round(rating, 2)
    })


out = pd.DataFrame(rows).sort_values("rating", ascending=False)

os.makedirs("data", exist_ok=True)
out.to_csv("data/player_ratings.csv", index=False)

print(out.head(20))
print("\nSaved: data/player_ratings.csv")
